version: 2.1

# Menggunakan Orbs (paket konfigurasi bawaan CircleCI)
orbs:
  slack: circleci/slack@4.12.5  # Mengaktifkan notifikasi Slack (opsional)

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17  # Gunakan Node.js terbaru (sesuaikan jika perlu)
  python-executor:
    docker:
      - image: cimg/python:3.11  # Gunakan Python 3.11 (sesuaikan jika perlu)

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: "Install dependencies"
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run tests"
          command: npm test

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Build application"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Deploy application"
          command: python deploy.py
      - slack/notify:
          event: fail
          channel: "#ci-notifications"
          message: "🚨 Deployment Failed in CircleCI!"

workflows:
  version: 2
  main-workflow:
    jobs:
      - setup:
          filters:
            branches:
              only: main
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
